### ISSUE TITLE
duplicate key value violates unique constraint "set_key_value_key"

### ISSUE THREAD

**Issue by Frazi1** [face-it/Hangfire.Tags#39]
While working on #35, I started off creating a unit-test to reproduce the error. 70% of the time, that test fails with the error described in #35. However, sometimes there is another exception saying ` Npgsql.PostgresException
23505: duplicate key value violates unique constraint "set_key_value_key"`

Full stack trace:

```Hangfire.Tags.PostgreSql.Tests.Hangfire.Tags.PostgreSql.Tests.Integration_ConcurrencyTests.AddTags_ShouldNotFail_WithConcurrencyError

Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.

Hangfire.BackgroundJobClientException
Background job creation failed. See inner exception for details.
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Hangfire.BackgroundJobClientExtensions.Create[T](IBackgroundJobClient client, Expression`1 methodCall, IState state)
   at Hangfire.Tags.PostgreSql.Tests.Hangfire.Tags.PostgreSql.Tests.Integration_ConcurrencyTests.<>c__DisplayClass3_0.<AddTags_ShouldNotFail_WithConcurrencyError>g__CreateJobs|1(JobType jobType, CancellationToken token) in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\tests\Hangfire.Tags.PostgreSql.Tests\Integration_ConcurrencyTests.cs:line 65
   at Hangfire.Tags.PostgreSql.Tests.Hangfire.Tags.PostgreSql.Tests.Integration_ConcurrencyTests.<>c__DisplayClass3_3.<AddTags_ShouldNotFail_WithConcurrencyError>b__4() in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\tests\Hangfire.Tags.PostgreSql.Tests\Integration_ConcurrencyTests.cs:line 75
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Hangfire.Tags.PostgreSql.Tests.Hangfire.Tags.PostgreSql.Tests.Integration_ConcurrencyTests.AddTags_ShouldNotFail_WithConcurrencyError() in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\tests\Hangfire.Tags.PostgreSql.Tests\Integration_ConcurrencyTests.cs:line 80
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

Npgsql.PostgresException
23505: duplicate key value violates unique constraint "set_key_value_key"
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.<>c__DisplayClass18_0.<AddToSet>b__0(NpgsqlConnection con)
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.Commit()
   at Hangfire.Tags.Storage.TagsStorage.AddTags(String jobid, IEnumerable`1 tags) in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\src\Hangfire.Tags\Storage\TagsStorage.cs:line 116
   at Hangfire.Tags.HangfireExtensions.AddTags(String jobid, String[] tags) in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\src\Hangfire.Tags\Extensions\HangfireExtensions.cs:line 19
   at Hangfire.Tags.HangfireExtensions.AddTags(String jobid, IEnumerable`1 tags) in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\src\Hangfire.Tags\Extensions\HangfireExtensions.cs:line 12
   at Hangfire.Tags.States.CreateJobFilter.OnCreated(CreatedContext filterContext) in D:\_Projects\Hangfire\Hangfire.Tags.Fraz\src\Hangfire.Tags\States\CreateJobFilter.cs:line 40
   at Hangfire.Client.BackgroundJobFactory.InvokeOnCreated(Tuple`2 x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.EmptyProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
   at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)



Test failed after have created 1887 jobs
```

## Environment
1. Hangfire.Tags 1.7.2
2. Hangfire.Tags.PostgreSql 1.8.0
3. Hangfire.PostgreSql 1.8.1
4. Hangfire.AspNetCore 1.7.19
5. .NET Core 3.1
6. Postgres 13 (latest docker images)
7. I7-10700K (16 cores)

## Steps to reproduce
1. Checkout commit: https://github.com/Frazi1/Hangfire.Tags/commit/b0705b63e785fd242bbeebc55cddd04661e0da47
2. `docker run --name postgres-hangfire -e POSTGRES_PASSWORD=test -p 5432:5432 -d postgres`
3. **IMPORTANT** Create a fresh DB instance for **each** test run. The error happens more often on a fresh DB.
4. Adjust the connection string in `testsettings.json` file, if needed
4. Run `AddTags_ShouldNotFail_WithConcurrencyError` unit-test

## Actual behavior
The unit test fails with either exception from #35, or with `duplicate key value violates unique constraint "set_key_value_key"` error.

You may have to re-run the unit test several times (make sure you run it on a fresh DB instance each time) to get this very exception.

I haven't tried researching this error yet. @erwin-faceit Have you seen it before? Any ideas? Maybe it is another subject for being handled by the retry policy from #35.

**Comment by Frazi1** [comment]
Should be fixed by https://github.com/frankhommers/Hangfire.PostgreSql/issues/198.

Closing.
