### ISSUE TITLE
Exceprion with Npgsql.NpgsqlConnection

### ISSUE THREAD

**Issue by excme** [face-it/Hangfire.Tags#47]
![image](https://user-images.githubusercontent.com/13168074/149161942-d87d307f-0d0f-4772-a2fc-334a5d388066.png)

```
Object of type 'System.Action`1[Npgsql.NpgsqlConnection]' cannot be converted to type 'System.Action`1[System.Data.IDbConnection]'.

System.ArgumentException: Object of type 'System.Action`1[Npgsql.NpgsqlConnection]' cannot be converted to type 'System.Action`1[System.Data.IDbConnection]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Hangfire.Tags.PostgreSql.PostgreSqlTagsTransaction.QueueCommand(Action`1 action)
   at Hangfire.Tags.PostgreSql.PostgreSqlTagsTransaction.ExpireSetValue(String key, String value, TimeSpan expireIn)
   at Hangfire.Tags.Storage.TagExpirationTransaction.Expire(String jobid, TimeSpan expireIn)
   at Hangfire.Tags.States.TagsCleanupStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.InvokeOnStateApplied(Tuple`2 x)
```

Have a exception on job finishing.

Hangfire 1.7.28
Hangfire.Tags.PostgreSql, Version=1.8.1.0
Hangfire.Tags, Version=1.7.1.0

**Comment by Sveer** [comment]
The same one on Hangfire 1.8 beta :(

**Comment by Akjo4712** [comment]
Same here with the following Versions. Anything I can do to help debugging this Issue?
- Hangfire.AspNetCore 1.7.28
- Hangfire.Console 1.4.2
- Hangfire.Postgresql 1.9.5
- Hangfire.Tags 1.8.1
- Hangfire.Tags.PostgreSql1.8.1

**Comment by Akjo4712** [comment]
@erwin-faceit, just spent some time on debugging this one, but I am unable to find the Problem. Could you please have a look?

**Comment by erwin-faceit** [comment]
During [this pull request](https://github.com/frankhommers/Hangfire.PostgreSql/pull/212) the interface of the QueueCommand method was changed in Hangfire.Postgresql. 

I've pushed a branch called issue/47. Can you pull that branch, compile it and test it?

It's one of the downsides of using reflection, unfortunately.

**Comment by Akjo4712** [comment]
@erwin-faceit: Thanks for your fast response. Is working for me when I build from branch issue/47.

**Comment by erwin-faceit** [comment]
I've just pushed version 1.9.5 to Nuget: https://www.nuget.org/packages/Hangfire.Tags.PostgreSql/1.9.5. It will be available shortly.

**Comment by Akjo4712** [comment]
Works, thank you @erwin-faceit!
