### ISSUE TITLE
The functions QueueCommand and AddCommand cannot be found error

### ISSUE THREAD

**Issue by muhammetustaoglu** [face-it/Hangfire.Tags#77]
After migration to Hangfire 1.8.6 tasks stopped running getting this error below. We use Hangfire.Tags 1.8.5

System.ArgumentException: The functions QueueCommand and AddCommand cannot be found.
   at Hangfire.Tags.SqlServer.SqlTagsTransaction..ctor(SqlServerStorageOptions options, IWriteOnlyTransaction transaction)
   at Hangfire.Tags.SqlServer.SqlTagsServiceStorage.GetTransaction(IWriteOnlyTransaction transaction)
   at Hangfire.Tags.Storage.TagExpirationTransaction.Persist(String jobid)
   at Hangfire.Tags.States.TagsCleanupStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.InvokeOnStateApplied(Tuple`2 x)

**Comment by 1bberto** [comment]
I'm facing the same issue

**Comment by erwin-faceit** [comment]
Migrate Hangfire.Tags to the preview version of FaceIT.Hangfire.Tags

**Comment by muhammetustaoglu** [comment]
Sorry, but this didnt help. There is a pending PR for this issue. Would you mind if you review it please?

> Migrate Hangfire.Tags to the preview version of FaceIT.Hangfire.Tags

**Comment by erwin-faceit** [comment]
I've merged the PR by @1bberto into [Faceit.Hangfire.Tags.MssqlServer-1.9.0b3](https://www.nuget.org/packages/FaceIT.Hangfire.Tags.SqlServer/1.9.0-beta.3). Thanks for the PR, @1bberto!

**Comment by fairking** [comment]
Is this released? I have the latest version from Nuget and I am getting this error as well.
```bash
ArgumentException: The functions QueueCommand and AddCommand cannot be found.
```

**Comment by erwin-faceit** [comment]
When using the correct package, it should. Make sure you’re NOT using Hangfire.Tags packages anymore, but FaceIT.Hangfire.Tags packages.
